version: '3.4'

services:
  phoneshop.webapi:
    image: ${DOCKER_REGISTRY-}phoneshopwebapi
    build:
      context: .
      dockerfile: Phoneshop.WebAPI/Dockerfile
    ports:
        - 8080:80
        - 4430:443

  sqlserver:
      image: mcr.microsoft.com/mssql/server:2022-latest    
      environment:
       - ACCEPT_EULA=YES
       - SA_PASSWORD=GeitenMekker21!
      ports:
        - 1433:1433
  frontend:
        image:  ${DOCKER_REGISTRY-}phoneshopangular
        build:
            context: Phoneshop.Angular/AngularPhoneshop
            dockerfile: Dockerfile
        ports:
            - 4200:4200
        command: ng serve --host 0.0.0.0